import { useEffect } from "react";
import { applyResolvedSeo, createFallbackSeo } from '@/exxonim/seo';
import { Button } from '@/exxonim/components/primitives/Button';
import { normalizePathname, routes } from "@/exxonim/routes";

interface NotFoundPageProps {
  pathname?: string;
}

/* ═══════════════════════════════════════════════════════════════
 * SkyClouds — procedural atmosphere (no image assets).
 *
 * A teal-tinted sky gradient with soft, wispy clouds generated by an
 * SVG fractal-noise filter (feTurbulence). Fully self-contained and
 * theme-aware: light misty sky by day, deep teal night by dark mode.
 * ═══════════════════════════════════════════════════════════════ */
function SkyClouds() {
  return (
    <div className="pointer-events-none absolute inset-0 -z-10 overflow-hidden bg-page">
      {/* Bright cloud-break behind the 404 (no new hue — keeps the one flat colour). */}
      <div className="absolute left-1/2 top-[40%] h-[42rem] w-[66rem] max-w-[130vw] -translate-x-1/2 -translate-y-1/2 rounded-[50%] bg-[radial-gradient(ellipse,rgba(255,255,255,0.9)_0%,rgba(255,255,255,0.5)_38%,transparent_66%)] blur-2xl dark:bg-[radial-gradient(ellipse,var(--color-accent-soft)_0%,transparent_62%)]" />

      {/* Photographic cloud bank — two procedural passes over a central band:
          (1) large soft masses for body, (2) finer wisps for texture. White puffs
          gain depth from strong underbelly shadows (contrast can't come from colour
          on the cream ground), so a real cloud bank gathers behind the 404. */}
      <svg
        className="absolute inset-0 h-full w-full dark:opacity-[0.08] [mask-image:linear-gradient(180deg,transparent_0%,#000_10%,#000_90%,transparent_100%)] [-webkit-mask-image:linear-gradient(180deg,transparent_0%,#000_10%,#000_90%,transparent_100%)]"
        preserveAspectRatio="xMidYMid slice"
        aria-hidden="true"
      >
        <defs>
          {/* Big billowy masses */}
          <filter id="nf-cloud-bank" x="-30%" y="-30%" width="160%" height="160%">
            <feTurbulence type="fractalNoise" baseFrequency="0.004 0.0065" numOctaves="5" seed="8" stitchTiles="stitch" result="noise" />
            <feComponentTransfer in="noise" result="shaped">
              <feFuncR type="linear" slope="0" intercept="1" />
              <feFuncG type="linear" slope="0" intercept="1" />
              <feFuncB type="linear" slope="0" intercept="1" />
              <feFuncA type="gamma" amplitude="1" exponent="3" offset="0" />
            </feComponentTransfer>
            <feGaussianBlur in="shaped" stdDeviation="4" />
            <feDropShadow dx="0" dy="16" stdDeviation="22" floodColor="#0c2f34" floodOpacity={0.4} />
          </filter>
          {/* Finer wisps riding on top */}
          <filter id="nf-cloud-wisps" x="-30%" y="-30%" width="160%" height="160%">
            <feTurbulence type="fractalNoise" baseFrequency="0.011 0.016" numOctaves="4" seed="27" stitchTiles="stitch" result="noise" />
            <feComponentTransfer in="noise" result="shaped">
              <feFuncR type="linear" slope="0" intercept="1" />
              <feFuncG type="linear" slope="0" intercept="1" />
              <feFuncB type="linear" slope="0" intercept="1" />
              <feFuncA type="gamma" amplitude="1" exponent="5" offset="0" />
            </feComponentTransfer>
            <feGaussianBlur in="shaped" stdDeviation="1.5" />
            <feDropShadow dx="0" dy="7" stdDeviation="9" floodColor="#0c2f34" floodOpacity={0.2} />
          </filter>
        </defs>
        <rect width="100%" height="100%" filter="url(#nf-cloud-bank)" opacity="0.95" />
        <rect width="100%" height="100%" filter="url(#nf-cloud-wisps)" opacity="0.7" />
      </svg>
    </div>
  );
}

export function NotFoundPage({ pathname }: NotFoundPageProps) {
  const normalizedPathname = normalizePathname(pathname);
  const showRequestedPath =
    Boolean(normalizedPathname) &&
    normalizedPathname !== normalizePathname(routes.home) &&
    normalizedPathname !== normalizePathname(routes.notFound);

  useEffect(() => {
    applyResolvedSeo(
      createFallbackSeo(routes.notFound, {
        title: "Page not found | Exxonim",
        description: "The Exxonim page you requested could not be found.",
        robots: "noindex,follow",
      })
    );
  }, []);

  return (
    <section className="relative flex min-h-[calc(100vh-60px)] flex-col items-center justify-center overflow-hidden px-6 py-16 text-center xl:min-h-[calc(100vh-68px)]">
      <SkyClouds />

      {/* Giant 404 — teal gradient dissolving into the clouds */}
      <p
        aria-hidden="true"
        className="select-none font-black leading-none tracking-tight text-[clamp(8rem,40vw,26rem)]"
        style={{
          backgroundImage:
            "linear-gradient(180deg, var(--color-accent) 0%, #2f8188 42%, var(--color-accent-secondary) 74%, rgba(127,188,193,0) 100%)",
          WebkitBackgroundClip: "text",
          backgroundClip: "text",
          WebkitTextFillColor: "transparent",
          color: "transparent",
          WebkitMaskImage: "linear-gradient(180deg, #000 55%, transparent 94%)",
          maskImage: "linear-gradient(180deg, #000 55%, transparent 94%)",
        }}
      >
        404
      </p>

      <h1 className="mt-2 text-3xl font-bold tracking-tight text-text sm:text-4xl md:text-5xl">
        Sorry, that page could not be found
      </h1>

      <p className="mt-4 max-w-md text-base text-text-muted sm:text-lg">
        The requested page either doesn&rsquo;t exist, or you don&rsquo;t have access to it.
      </p>

      {showRequestedPath ? (
        <p className="mt-5 text-sm text-text-soft">
          Requested path
          <code className="ml-2 rounded bg-accent-soft px-2 py-0.5 font-mono text-accent">{pathname}</code>
        </p>
      ) : null}

      <div className="mt-10">
        <Button size="hero" variant="primary" href={routes.home}>
          Go Back Home
        </Button>
      </div>
    </section>
  );
}
