/**
 * Blog categories hook.
 *
 * Fallback chain:
 *   1. Live API (FastAPI backend)
 *   2. Blog snapshot (/snapshot/blog/blog-categories.json — auto-generated by backend)
 *   3. Empty array (no categories to show)
 *
 * No hardcoded fallback. The snapshot is the source of truth when the API is down.
 */
import { useQuery } from "@tanstack/react-query";
import { fetchPublicBlogCategoriesRaw } from "@/exxonim/services/blogService";
import { fetchWithBlogSnapshotFallback } from "@/exxonim/services/staticFallbackService";
import { mapBlogCategory } from "@/exxonim/utils/contentMappers";
import type { BlogCategory } from "@/exxonim/types";

export function useBlogCategories() {
  const query = useQuery<BlogCategory[]>({
    queryKey: ["blog", "categories"],
    queryFn: async () => {
      const raw = await fetchWithBlogSnapshotFallback(fetchPublicBlogCategoriesRaw, "blog-categories");
      const arr = Array.isArray(raw) ? raw : [];
      return arr.map((c) => mapBlogCategory(c) as BlogCategory);
    },
    staleTime: 1000 * 60 * 5, // 5 minutes
    retry: 1,
  });

  return {
    ...query,
    data: query.data ?? [],
    isPending: query.isPending,
  };
}
