/**
 * Single blog post hook.
 *
 * Fallback chain:
 *   1. Live API (FastAPI backend)
 *   2. Blog snapshot (/snapshot/blog/blog-post-{slug}.json — auto-generated by backend)
 *   3. undefined (caller shows loading/not-found state)
 *
 * No hardcoded fallback. The snapshot is the source of truth when the API is down.
 */
import { useQuery } from "@tanstack/react-query";
import { fetchPublicBlogPostBySlugRaw } from "@/exxonim/services/blogService";
import { fetchWithBlogSnapshotFallback } from "@/exxonim/services/staticFallbackService";
import { mapBlogPost } from "@/exxonim/utils/contentMappers";

export function useBlogPost(slug: string | null) {
  const query = useQuery({
    queryKey: ["blog", "post", slug],
    queryFn: async () => {
      const raw = await fetchWithBlogSnapshotFallback(
        () => fetchPublicBlogPostBySlugRaw(slug as string),
        `blog-post-${slug}`
      );
      return mapBlogPost(raw);
    },
    enabled: Boolean(slug),
    staleTime: 1000 * 30, // 30 seconds
    retry: (failureCount, error) => {
      const status = (error as { response?: { status?: number } } | null)?.response?.status;
      if (status === 404) return false;
      return failureCount < 2;
    },
  });

  return {
    ...query,
    data: query.data,
    isPending: query.isPending,
  };
}
