/**
 * CACHE ARCHITECTURE (5-layer):
 * ──────────────────────────────
 * Layer 0: TanStack memory cache (in-memory, instant, same session)
 * Layer 1: persistQueryClient (localStorage, instant, 24h max age)
 * Layer 2: Live API (FastAPI backend, background refetch)
 * Layer 3: /fallback/*.json (same server, webhook-updated)
 * Layer 4: Hardcoded placeholderData (in JS bundle, always available)
 *
 * FLOW ON REFRESH:
 *   1. Service Worker serves cached JS/CSS/images instantly
 *   2. persistQueryClient hydrates from localStorage → render instantly
 *   3. API call fires in background → updates if changed (no flicker)
 *   4. If API fails → /fallback/*.json loads → persists to localStorage
 *   5. If fallback missing → hardcoded placeholderData shows (in JS bundle)
 *
 * This file implements Layers 2-4. See queryClient.ts for Layers 0-1.
 */

/**
 * Static Fallback Service
 * ───────────────────────
 * Reads /fallback/{key}.json files generated by scripts/refresh-fallbacks.mjs.
 *
 * These files are auto-updated when admin saves changes (webhook-triggered).
 * They serve as Layer 3 emergency content between the live API and the
 * hardcoded TypeScript defaults.
 *
 * ARCHITECTURE (priority order):
 *   Layer 0: TanStack Memory Cache (current session)
 *   Layer 1: persistQueryClient (localStorage) - instant for returning visitors
 *   Layer 2: Live API - fresh data from database
 *   Layer 3: /fallback/*.json - emergency, same server, refreshed on admin save
 *   Layer 4: placeholderData (hardcoded TypeScript) - extreme disaster only
 *
 * FLOW FOR RETURNING VISITOR:
 *   1. Load persisted cache from localStorage → render instantly
 *   2. Call API in background → update if changed
 *   → No flicker, no content jumping
 *
 * FLOW FOR FIRST VISITOR (API works):
 *   1. No cache → show placeholderData briefly
 *   2. API responds → render real data → save to cache
 *
 * FLOW FOR FIRST VISITOR (API down):
 *   1. No cache → show placeholderData briefly
 *   2. API fails → try JSON fallback
 *   3. JSON available → render JSON data → save to cache
 *
 * FLOW FOR FIRST VISITOR (API down, JSON missing):
 *   1. No cache → show placeholderData briefly
 *   2. API fails → JSON missing → query errors
 *   3. Component falls back to hardcoded defaults via ternary
 */

/* ── Module-level cache ──────────────────────────────── */
const loaded: Map<string, unknown> = new Map();

/**
 * Load a static fallback JSON file from /fallback/{key}.json.
 * Used internally by fetchWithJsonFallback.
 */
async function loadStaticFallback<T>(
  key: string,
  timeoutMs = 800
): Promise<T | undefined> {
  if (loaded.has(key)) {
    return loaded.get(key) as T;
  }

  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    const response = await fetch(`/fallback/${key}.json`, {
      signal: controller.signal,
      headers: { Accept: "application/json" },
    });
    clearTimeout(timer);

    if (!response.ok) {
      if (response.status === 404) return undefined;
      return undefined;
    }

    const raw = (await response.json()) as {
      _meta?: { generatedAt?: string; source?: string };
      data?: T;
    } | T;

    // Support both envelope format ({ _meta, data }) and raw format
    const data =
      raw && typeof raw === "object" && "data" in raw && "_meta" in raw
        ? (raw as { data: T }).data
        : (raw as T);

    loaded.set(key, data);
    return data;
  } catch {
    return undefined;
  }
}

/**
 * Fetch with JSON fallback - the standard queryFn wrapper.
 *
 * Tries the API first. If the API fails, falls back to the
 * static JSON file. If both fail, throws (the query goes to
 * error state, and placeholderData / component defaults handle it).
 *
 * When the JSON fallback succeeds, its data becomes the query's
 * "real" data and gets persisted to localStorage via persistQueryClient.
 * This means next visit, the user sees the JSON data instantly from cache,
 * even before the API call completes.
 *
 * @example
 * ```ts
 * queryFn: () => fetchWithJsonFallback(
 *   () => getSiteSetting<BrandAssets>("brand"),
 *   "site-settings-brand"
 * ),
 * ```
 */
export async function fetchWithJsonFallback<T>(
  apiFn: () => Promise<T>,
  fallbackKey: string
): Promise<T> {
  try {
    return await apiFn();
  } catch {
    const fallback = await loadStaticFallback<T>(fallbackKey);
    if (fallback !== undefined) return fallback;
    throw new Error(`API and JSON fallback both failed for: ${fallbackKey}`);
  }
}
