/**
 * Static Fallback Service
 * ───────────────────────
 * Reads /fallback/{key}.json files generated by scripts/refresh-fallbacks.mjs.
 *
 * These files are auto-updated when admin saves changes (webhook-triggered).
 * They serve as Layer 3 emergency content between the live API and the
 * hardcoded TypeScript defaults.
 *
 * ARCHITECTURE (priority order):
 *   Layer 0: TanStack Memory Cache (current session)
 *   Layer 1: persistQueryClient (localStorage) - instant for returning visitors
 *   Layer 2: Live API - fresh data from database
 *   Layer 3: /fallback/*.json - emergency, same server, refreshed on admin save
 *   Layer 4: placeholderData (hardcoded TypeScript) - extreme disaster only
 *
 * FLOW FOR RETURNING VISITOR:
 *   1. Load persisted cache from localStorage → render instantly
 *   2. Call API in background → update if changed
 *   → No flicker, no content jumping
 *
 * FLOW FOR FIRST VISITOR (API works):
 *   1. No cache → show placeholderData briefly
 *   2. API responds → render real data → save to cache
 *
 * FLOW FOR FIRST VISITOR (API down):
 *   1. No cache → show placeholderData briefly
 *   2. API fails → try JSON fallback
 *   3. JSON available → render JSON data → save to cache
 *
 * FLOW FOR FIRST VISITOR (API down, JSON missing):
 *   1. No cache → show placeholderData briefly
 *   2. API fails → JSON missing → query errors
 *   3. Component falls back to hardcoded defaults via ternary
 */

/* ── Module-level cache ──────────────────────────────── */
const loaded: Map<string, unknown> = new Map();

/* ── Eager preload map ────────────────────────────────── */
const preloads: Map<string, Promise<unknown>> = new Map();

/**
 * Register an eager preload for a static fallback file.
 * Call this at module top-level (not inside a component or effect).
 */
export function preloadStaticFallback<T>(key: string): Promise<T | undefined> {
  const existing = preloads.get(key);
  if (existing) return existing as Promise<T | undefined>;

  const promise = loadStaticFallback<T>(key).then((val) => {
    if (typeof val !== "undefined") {
      loaded.set(key, val);
    }
    return val;
  });

  preloads.set(key, promise);
  return promise;
}

/**
 * Get a previously loaded static fallback value synchronously.
 * Returns undefined if the file hasn't finished loading or doesn't exist.
 */
export function getStaticFallback<T>(key: string): T | undefined {
  return loaded.get(key) as T | undefined;
}

/**
 * Load a static fallback JSON file from /fallback/{key}.json.
 * Public API - used by fetchWithJsonFallback and preloadStaticFallback.
 */
export async function loadStaticFallback<T>(
  key: string,
  timeoutMs = 800
): Promise<T | undefined> {
  if (loaded.has(key)) {
    return loaded.get(key) as T;
  }

  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    const response = await fetch(`/fallback/${key}.json`, {
      signal: controller.signal,
      headers: { Accept: "application/json" },
    });
    clearTimeout(timer);

    if (!response.ok) {
      if (response.status === 404) return undefined;
      return undefined;
    }

    const raw = (await response.json()) as {
      _meta?: { generatedAt?: string; source?: string };
      data?: T;
    } | T;

    // Support both envelope format ({ _meta, data }) and raw format
    const data =
      raw && typeof raw === "object" && "data" in raw && "_meta" in raw
        ? (raw as { data: T }).data
        : (raw as T);

    loaded.set(key, data);
    return data;
  } catch {
    return undefined;
  }
}

/**
 * Fetch with JSON fallback - the standard queryFn wrapper.
 *
 * Tries the API first. If the API fails, falls back to the
 * static JSON file. If both fail, throws (the query goes to
 * error state, and placeholderData / component defaults handle it).
 *
 * When the JSON fallback succeeds, its data becomes the query's
 * "real" data and gets persisted to localStorage via persistQueryClient.
 * This means next visit, the user sees the JSON data instantly from cache,
 * even before the API call completes.
 *
 * @example
 * ```ts
 * queryFn: () => fetchWithJsonFallback(
 *   () => getSiteSetting<BrandAssets>("brand"),
 *   "site-settings-brand"
 * ),
 * ```
 */
export async function fetchWithJsonFallback<T>(
  apiFn: () => Promise<T>,
  fallbackKey: string
): Promise<T> {
  try {
    return await apiFn();
  } catch {
    const fallback = await loadStaticFallback<T>(fallbackKey);
    if (fallback !== undefined) return fallback;
    throw new Error(`API and JSON fallback both failed for: ${fallbackKey}`);
  }
}
