import type { ServiceCatalogItem, ServiceSegment } from '@/exxonim/types/service-catalog';

export const fallbackSegments: ServiceSegment[] = [
  { id: 'seg-1', name: 'Local Entrepreneurs', slug: 'local-entrepreneurs', sort_order: 10 },
  { id: 'seg-2', name: 'Foreign Investors', slug: 'foreign-investors', sort_order: 20 },
  { id: 'seg-3', name: 'Enterprises', slug: 'enterprises', sort_order: 30 },
  { id: 'seg-4', name: 'NGOs', slug: 'ngos', sort_order: 40 },
];

export const fallbackCategories: string[] = [
  'Business Setup',
  'Compliance Support',
  'Work Permits & Foreign Investment',
  'NGOs & Non-Profits',
];

export const fallbackServices: ServiceCatalogItem[] = [
  {
    id: 'svc-1',
    title: 'Company Registration',
    slug: 'company-registration',
    category: 'Business Setup',
    primary_segment: ['Local Entrepreneurs', 'Foreign Investors', 'Enterprises'],
    badge: 'Most Popular',
    short_description:
      'Legally trade within 5–10 business days. We handle everything from name search to your Certificate of Incorporation.',
    deliverables: [
      'BRELA name search & reservation',
      'Certificate of Incorporation (COI)',
      'TIN Application',
      'Business License Assistance',
    ],
    deliverables_full: [
      'Company seal production',
      'Shareholder & director register setup',
      'Notarised document package',
      'Bank account introduction support',
    ],
    cta_text: 'Get Started',
    cta_link: '/contact?service=company-registration',
    status: 'published',
    sort_order: 10,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-2',
    title: 'Business Name Registration',
    slug: 'business-name-registration',
    category: 'Business Setup',
    primary_segment: ['Local Entrepreneurs'],
    badge: null,
    short_description:
      'Secure your sole proprietorship or trading name through BRELA with minimal paperwork.',
    deliverables: [
      'Sole proprietorship registration',
      'Trading name reservation',
      'BRELA filing confirmation',
      'Digital certificate copy',
    ],
    deliverables_full: null,
    cta_text: 'Get Started',
    cta_link: '/contact?service=business-name-registration',
    status: 'published',
    sort_order: 20,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-3',
    title: 'NGO Registration',
    slug: 'ngo-registration',
    category: 'Business Setup',
    primary_segment: ['NGOs'],
    badge: 'Non-Profit Focus',
    short_description:
      'Complete non-profit entity setup, from constitution drafting to initial compliance guidance.',
    deliverables: [
      'NGO entity registration with authorities',
      'Constitution drafting assistance',
      'Initial governance compliance roadmap',
      'Donor-readiness pack',
    ],
    deliverables_full: [
      'Registration with Ministry of Community Development',
      'Certificate of Registration expedited',
      'Governance policy templates',
    ],
    cta_text: 'Get Started',
    cta_link: '/contact?service=ngo-registration',
    status: 'published',
    sort_order: 30,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-4',
    title: 'Trademark Registration',
    slug: 'trademark-registration',
    category: 'Business Setup',
    primary_segment: ['Local Entrepreneurs', 'Foreign Investors', 'Enterprises'],
    badge: 'Brand Protection',
    short_description:
      'Protect your brand name, logo, or slogan through the BRELA intellectual property office.',
    deliverables: [
      'BRELA trademark availability search',
      'Full trademark application filing',
      'Intellectual property certificate upon registration',
      '10-year renewal tracking',
    ],
    deliverables_full: null,
    cta_text: 'Get Started',
    cta_link: '/contact?service=trademark-registration',
    status: 'published',
    sort_order: 40,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-5',
    title: 'TIN Application',
    slug: 'tin-application',
    category: 'Business Setup',
    primary_segment: ['Local Entrepreneurs', 'Foreign Investors', 'Enterprises'],
    badge: null,
    short_description:
      'Get your Tax Identification Number quickly for tax compliance and business operations.',
    deliverables: [
      'TIN application preparation & submission',
      'TRA account setup',
      'E-filing credentials',
      'Tax registration certificate',
    ],
    deliverables_full: null,
    cta_text: 'Get Started',
    cta_link: '/contact?service=tin-application',
    status: 'published',
    sort_order: 50,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-6',
    title: 'Business License Applications',
    slug: 'business-license',
    category: 'Business Setup',
    primary_segment: ['Local Entrepreneurs', 'Enterprises'],
    badge: null,
    short_description:
      'Securing your sector-specific licence to operate fully and legally.',
    deliverables: [
      'Identification of required licences per sector',
      'Application preparation and submission',
      'Regulatory follow-up and approval tracking',
      'Post-licence compliance briefing',
    ],
    deliverables_full: null,
    cta_text: 'Get Started',
    cta_link: '/contact?service=business-license',
    status: 'published',
    sort_order: 60,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-7',
    title: 'Annual Returns',
    slug: 'annual-returns',
    category: 'Compliance Support',
    primary_segment: ['Local Entrepreneurs', 'Enterprises', 'NGOs'],
    badge: 'Deadline-Driven',
    short_description:
      'Never miss your BRELA annual return filing again, including beneficial ownership updates.',
    deliverables: [
      'BRELA annual return preparation & filing',
      'Beneficial ownership update submission',
      'Late filing prevention calendar',
      'Electronic filing confirmation',
    ],
    deliverables_full: [
      '30-day advance reminders',
      'Document audit before submission',
    ],
    cta_text: 'Get Started',
    cta_link: '/contact?service=annual-returns',
    status: 'published',
    sort_order: 70,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-8',
    title: 'Statutory Filings',
    slug: 'statutory-filings',
    category: 'Compliance Support',
    primary_segment: ['Local Entrepreneurs', 'Enterprises'],
    badge: null,
    short_description:
      'PAYE, SDL, WCF, and NSSF filings - all prepared and submitted on schedule.',
    deliverables: [
      'Payroll compliance filing (PAYE, SDL)',
      'WCF contribution filing',
      'NSSF employer return filing',
      'Deadline tracking with advance reminders',
    ],
    deliverables_full: null,
    cta_text: 'Get Started',
    cta_link: '/contact?service=statutory-filings',
    status: 'published',
    sort_order: 80,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-9',
    title: 'Regulatory Renewals',
    slug: 'regulatory-renewals',
    category: 'Compliance Support',
    primary_segment: ['Local Entrepreneurs', 'Foreign Investors', 'Enterprises'],
    badge: 'Proactive Tracking',
    short_description:
      'Proactive tracking and timely processing of all your licences, permits, and regulatory renewals.',
    deliverables: [
      'Central renewal calendar for all permits',
      '60-, 30-, and 7-day advance reminders',
      'Document re-submission and fee payment coordination',
      'Renewal confirmation and updated certificates',
    ],
    deliverables_full: null,
    cta_text: 'Get Started',
    cta_link: '/contact?service=regulatory-renewals',
    status: 'published',
    sort_order: 90,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-10',
    title: 'Operational Advisory',
    slug: 'operational-advisory',
    category: 'Compliance Support',
    primary_segment: ['Enterprises'],
    badge: 'Enterprise Tier',
    short_description:
      'Structured compliance guidance for teams managing multiple obligations across subsidiaries.',
    deliverables: [
      'Dedicated compliance advisor',
      'Document management system access',
      'Quarterly compliance review meetings',
      'Forward-looking compliance strategy',
    ],
    deliverables_full: null,
    cta_text: 'Discuss My Case',
    cta_link: '/contact?service=operational-advisory',
    status: 'published',
    sort_order: 100,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-11',
    title: 'Work Permit Applications',
    slug: 'work-permit',
    category: 'Work Permits & Foreign Investment',
    primary_segment: ['Foreign Investors'],
    badge: 'Foreign Investors',
    short_description:
      'Hassle-free processing for Class A, Class B, and residence permits. Direct liaison with Ministry of Labour.',
    deliverables: [
      'Pre-application eligibility assessment',
      'Document preparation & legalisation',
      'Direct filing with immigration',
      'Real-time status tracking',
    ],
    deliverables_full: [
      'Work permit certificate delivery',
      'Renewal coordination',
    ],
    cta_text: 'Get Started',
    cta_link: '/contact?service=work-permit',
    status: 'published',
    sort_order: 110,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-12',
    title: 'TIC / TISEZA Registration',
    slug: 'tic-registration',
    category: 'Work Permits & Foreign Investment',
    primary_segment: ['Foreign Investors'],
    badge: 'Investment Focus',
    short_description:
      'Investment centre registration and compliance facilitation for foreign-owned entities.',
    deliverables: [
      'TIC/TISEZA registration application',
      'Sector-specific incentive identification',
      'Investment certificate processing',
      'Ongoing investment compliance tracking',
    ],
    deliverables_full: null,
    cta_text: 'Get Started',
    cta_link: '/contact?service=tic-registration',
    status: 'published',
    sort_order: 120,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-13',
    title: 'Foreign Company Registration',
    slug: 'foreign-company-reg',
    category: 'Work Permits & Foreign Investment',
    primary_segment: ['Foreign Investors', 'Enterprises'],
    badge: null,
    short_description:
      'Branch office or subsidiary setup for international businesses entering Tanzania.',
    deliverables: [
      'Certificate of Compliance with BRELA',
      'Cross-border document legalisation',
      'Local directorship arrangement guidance',
      'Post-registration compliance roadmap',
    ],
    deliverables_full: null,
    cta_text: 'Get Started',
    cta_link: '/contact?service=foreign-company-reg',
    status: 'published',
    sort_order: 130,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-14',
    title: 'NGO Registration (Enhanced)',
    slug: 'ngo-registration-enhanced',
    category: 'NGOs & Non-Profits',
    primary_segment: ['NGOs'],
    badge: 'Donor-Ready',
    short_description:
      'Complete NGO setup, registration with all relevant authorities, and a compliance baseline for donor confidence.',
    deliverables: [
      'Registration with Ministry of Community Development',
      'Certificate of Registration',
      'Constitution aligned with NGO Act',
      'Initial governance & reporting framework',
    ],
    deliverables_full: [
      'Tax exemption certificate guidance',
      'Board minute templates',
    ],
    cta_text: 'Get Started',
    cta_link: '/contact?service=ngo-registration-enhanced',
    status: 'published',
    sort_order: 140,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'svc-15',
    title: 'Compliance for NGOs',
    slug: 'ngo-compliance',
    category: 'NGOs & Non-Profits',
    primary_segment: ['NGOs'],
    badge: null,
    short_description:
      'Annual reporting, donor compliance, and governance documentation for established non-profits.',
    deliverables: [
      'Annual activity & financial report preparation',
      'Donor compliance attestation',
      'Board meeting minutes & governance file',
      'Tax exemption certificate renewal support',
    ],
    deliverables_full: null,
    cta_text: 'Get Started',
    cta_link: '/contact?service=ngo-compliance',
    status: 'published',
    sort_order: 150,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
];
